### ISSUE TITLE
driver.Requests is empty with firefox driver

### ISSUE THREAD

**Issue by hasanasim** [wkeeling/selenium-wire#210]
im trying to run the code snippet in the docs but my `driver.Requests` doesn't return anything. 

```
from seleniumwire import webdriver  # Import from seleniumwire

# Create a new instance of the Firefox driver
driver = webdriver.Firefox(seleniumwire_options={'port':6000})

# Go to the Google home page
driver.get('https://www.google.com')

driver.requests
```
driver.requests returns [] 
seleniumwire version: 4.0.2, selenium version 3.141.0, python 3.7.5

**Comment by wkeeling** [comment]
Is there a specific reason why you've configured Selenium Wire to use port 6000? If you do this, you'll also need to manually configure Firefox's proxy settings to use port 6000.

If you omit the port then Selenium Wire will do the configuration automatically.

**Comment by hasanasim** [comment]
No particular reason for 6000, if i don't configure the port i get an error.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hasan.asim/.pyenv/versions/ffscrapers3.7.5/lib/python3.7/site-packages/seleniumwire/webdriver.py", line 57, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/hasan.asim/.pyenv/versions/ffscrapers3.7.5/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/Users/hasan.asim/.pyenv/versions/ffscrapers3.7.5/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/hasan.asim/.pyenv/versions/ffscrapers3.7.5/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/hasan.asim/.pyenv/versions/ffscrapers3.7.5/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/hasan.asim/.pyenv/versions/ffscrapers3.7.5/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: httpProxy is not a valid URL: ::ffff:127.0.0.1:51910

```

**Comment by wkeeling** [comment]
Ok I see the issue. An IPv6 socket has been created, but Selenium Wire isn't wrapping the address in square brackets when creating the proxy URL. I'll get a fix out ASAP. Thanks!

**Comment by hasanasim** [comment]
Awesome, thank you!

**Comment by wkeeling** [comment]
There's a new version of Selenium Wire available (v4.0.3) which should fix this issue.

**Comment by Shakis87** [comment]
driver.requests is still an empty string for me on the updated version.

`swoptions = {
    'proxy': {
        'http': f'http://{proxy}',
        'https': f'https://{proxy}',
    }
}

driver = webdriver.Firefox(seleniumwire_options=swoptions,  executable_path='geckodriver.exe') 
driver.get('https://bbc.co.uk')
print(driver.requests)`

**Comment by wkeeling** [comment]
@Shakis87 Does it work if you omit the proxy?

**Comment by Shakis87** [comment]
I removed all the sw options and it still won't work, in another part of my script I do set a normal selenium/firefox profile but it isn't used, I'll try removing that too


```
driver = webdriver.Firefox(executable_path='geckodriver.exe')
driver.get('https://bbc.co.uk')
print(driver.requests)
```
output: []

**Comment by Shakis87** [comment]
Okay it seems to have been something in my code that was causing it to mess up, sorry for the inconveneince. The following wokrs:

```
from seleniumwire import webdriver
from selenium import webdriver as normal_webdriver
import time
import random

proxy_list = [
    # list of my proxy IPs
]
proxy = random.choice(proxy_list)

profile = normal_webdriver.FirefoxProfile()
# Set various profile options
profile.update_preferences()

swoptions = {
    'proxy': {
        'http': f'http://{proxy}',
        'https': f'https://{proxy}',
    },
    'ignore_http_methods': [],
    # 'port': int(PROXY_PORT),
}

driver = webdriver.Firefox(seleniumwire_options=swoptions, firefox_profile=profile, executable_path='geckodriver.exe')
driver.get('https://bbc.co.uk')
time.sleep(5)
print(driver.requests)
```

This spam a few errors though:

```
127.0.0.1:55451: Client Handshake failed. The client may not trust Selenium Wire's certificate for firefox.settings.services.mozilla.com.
127.0.0.1:55464: Client Handshake failed. The client may not trust Selenium Wire's certificate for firefox.settings.services.mozilla.com.
127.0.0.1:55475: Client Handshake failed. The client may not trust Selenium Wire's certificate for firefox.settings.services.mozilla.com.
127.0.0.1:55503: Client Handshake failed. The client may not trust Selenium Wire's certificate for firefox.settings.services.mozilla.com.
```

But I think I can get everything to work from here.
