### ISSUE TITLE
Proxy Auth not working with disable_capture=True

### ISSUE THREAD

**Issue by steathy** [wkeeling/selenium-wire#264]
Every time when chromedriver is launched using selenium-wire with proxy authentication, it pops up a small window asking for proxy username and password like this:

Sign in
The proxy http://127.0.0.1:xxxxx requires a username and password.
Username: ________________________________
Password:  ________________________________

I checked many times and assure that proxy auth was set up correctly in my code. The same code&chromedriver.exe runs fine on another computer.  

windows 10 LTSC 1809
Chrome 89.0.4389.114
selenium  3.141.0
selenium-wire  4.2.3

**Comment by wkeeling** [comment]
Chrome will pop up the username/password window when the username and password are incorrect. Is there a copy/paste error in the username/password, or does the username/password contain a special character that hasn't been copied correctly perhaps?

Can you share all the code (obviously hide the username/password) and we can then check whether that looks correct.

**Comment by steathy** [comment]
> Chrome will pop up the username/password window when the username and password are incorrect. Is there a copy/paste error in the username/password, or does the username/password contain a special character that hasn't been copied correctly perhaps?
> 
> Can you share all the code (obviously hide the username/password) and we can then check whether that looks correct.

After hours of debugging, I recalled that my code was originally written with selenium-wire 3.0.3. Therefore I downgraded to 3.0.3 and it worked. Then I tried every version and found out it broke starting from version 4.2.0. I don't know where to find 4.2.0 release notes (not github expert). Otherwise I could dig deeper to see what happened there.

My code looks like this:
`
sw_options = {
        'disable_capture': True
    }

sw_options['proxy'] = {'http': 'http://user:pwd@xxx.xxx.xxx.xxx:1234',
    'https': 'http://user:pwd@xxx.xxx.xxx.xxx:1234',
    'no_proxy': 'localhost,127.0.0.1'}

chromedriver_file_name = 'chromedriver.exe'
if sys.platform in ("linux",):
    chromedriver_file_name = 'chromedriver'

try:
    driver = Chrome(executable_path=os.path.join(os.path.dirname(
        os.path.abspath(__file__)), chromedriver_file_name), options=chrome_options, seleniumwire_options=sw_options)
    return driver
except Exception as e:
    print('Fail to initialize a customized chrome driver!')
    print(e)
`

**Comment by wkeeling** [comment]
Many thanks for taking the time to debug. 

It seems that the `disable_capture` option that was introduced in 4.2.0 is the cause of the problem. When this option is set to `True`, the automatic proxy authentication mechanism does not kick in, causing the browser to trigger the popup for manual entry. That's definitely a bug, so I'll investigate and get a fix in. In the meantime, you'll need to set `disable_capture` to `False` (or leave it out) to work around the problem.

**Comment by steathy** [comment]
> Many thanks for taking the time to debug.
> 
> It seems that the `disable_capture` option that was introduced in 4.2.0 is the cause of the problem. When this option is set to `True`, the automatic proxy authentication mechanism does not kick in, causing the browser to trigger the popup for manual entry. That's definitely a bug, so I'll investigate and get a fix in. In the meantime, you'll need to set `disable_capture` to `False` (or leave it out) to work around the problem.

Yeah confirmed. After removing `'disable_capture': True` I got the code working again. Great we figured it out:)

I am looking forward to you fix. Thank you!

**Comment by apollo17march** [comment]
> Many thanks for taking the time to debug.
> 
> It seems that the `disable_capture` option that was introduced in 4.2.0 is the cause of the problem. When this option is set to `True`, the automatic proxy authentication mechanism does not kick in, causing the browser to trigger the popup for manual entry. That's definitely a bug, so I'll investigate and get a fix in. In the meantime, you'll need to set `disable_capture` to `False` (or leave it out) to work around the problem.

This is the same issue as https://github.com/wkeeling/selenium-wire/issues/260. Waiting for the fix and thank you for this awesome library.

**Comment by wkeeling** [comment]
Fixed in 4.2.4. @steathy are you able to confirm all good your end?

**Comment by voxvici** [comment]
Still popping up on fedora 33, upgraded from version 4.2.2 to 4.2.4. Just had a similar case where request capture wasn't needed

**Comment by steathy** [comment]
> Fixed in 4.2.4. @steathy are you able to confirm all good your end?

Thanks. Tested working now. Cheers!

**Comment by htdung167** [comment]
Hi, 
I still have this problem with selenium==4.4.3, selenium-wire==5.0.0. I used multithreading, each in each one i randomize the proxy in the list, there are about 3 happening on 8 threads concurrently.
![image](https://user-images.githubusercontent.com/73953274/192659543-923a2b2a-5712-4366-9f4c-82f621d91cf6.png)
